services:
  - type: web
    name: fencing-center
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn fencing_center.wsgi"
    staticPublishPath: static
    autoDeploy: true